# PreCommit:
#   Pep8:
#     enabled: true
#     on_warn: fail # Treat all warnings as failures
#   Pep257:
#     enabled: true
#     on_warn: fail
#     command: ['pep257', '--ignore=D300,D400,D100,D203,D102,D202']
#   HardTabs:
#     enabled: true
#     on_warn: fail
